# Generated by Django 6.0.6 on 2026-07-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('te', 'Telugu'), ('ta', 'Tamil'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('mr', 'Marathi'), ('bn', 'Bengali')], default='en', max_length=2),
        ),
    ]
