# Generated by Django 6.0.6 on 2026-08-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_booking_confirmation_email_sent_booking_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='YouTube watch/embed/youtu.be link', null=True),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['language', 'rating'], name='movie_lang_rating_idx'),
        ),
    ]
